# docker-compose.yml

version: "3.8"

services:
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwer1234
    volumes:
      - ./server/src/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/package.json:/app/package.json
    ports:
      - "3000:3000"
    # environment:
    # - NODE_ENV=development
    env_file:
      - ./.env
